### ISSUE TITLE
problèmes de plugin ? 

### ISSUE THREAD

**Issue by xlyric** [messagerie-melanie2/Roundcube-Mel#1]
Thomas, 

j'ai tenté de mettre à jour un roundcube MCE fonctionnel vers la version plus présente présente sur le git. 

j'arrive à la page d'authentification, par contre une fois connecté, page blanche et j'ai ce genre de message dans errors.log

[03-Jul-2020 16:09:21 Europe/Berlin] PHP Warning:  count(): Parameter must be an array or an object that implements Countable  in  /var/www/html/webmail/plugins/mce/mce.php on line 300
[03-Jul-2020 16:09:21 Europe/Berlin] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/webmail/plugins/mce/mce.php on line 351
[03-Jul-2020 16:09:21 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function Q() in
/var/www/html/webmail/plugins/mce_labels_sync/mce_labels_sync.php:165
Stack trace:
#0 /var/www/html/webmail/program/lib/Roundcube/rcube_plugin_api.php(100): mce_labels_sync->init()
#1 /var/www/html/webmail/program/include/rcmail.php(137): rcube_plugin_api->init(Object(rcmail), 'mail')
#2 /var/www/html/webmail/program/include/rcmail.php(78): rcmail->startup()
#3 /var/www/html/webmail/index.php(43): rcmail::get_instance(0, NULL)
#4 {main} 
   thrown in
/var/www/html/webmail/plugins/mce_labels_sync/mce_labels_sync.php on line 165

**Comment by xlyric** [comment]
trouvé la solution en m'inspirant d'un cas similaire sur le net : 

L165 : 
-                 'content' => Q($this->gettext('labels')), // maybe put translated version of "Labels" here?
+                 'content' => rcube::Q($this->gettext('labels')), // maybe put translated version of "Labels" here?

**Comment by tpayen** [comment]
Bonjour Cyril,

je ne suis pas sur de saisir exactement ce que tu fais mais tu as l'air d'avoir récupéré la version Roundcube Mel venant de github et d'y avoir ajouté les plugins mce venant de la maquette. Les plugins mce étant assez anciens tu as visiblement des erreurs d'incompatibilité avec la version actuelle de Roundcube (et surement de PHP 7).

Il vaut mieux remplacer entièrement le webmail de la maquette mce par une release 1.4.8.1 qui peut venir soit de la forge mce, soit de la forge github (qui sont identiques), les plugins ne sont plus en mce* mais en mel* mais sont équivalent et plus récents

**Comment by xlyric** [comment]
c'est l'idée, je suis partis de la version de la maquette, récupéré la nouvelle version sur le git et fait un ./bin/upgrade.sh
puis récupéré les plugins et mis à jours suivant le process de copie indiqué dans la doc ( copie plugin et skin dans le répertoire de l'appli ) 

je vais tenter de refaire une installe propre ( vu que je n'ai pas réussi à faire marcher la boutique la 1ere fois )

**Comment by xlyric** [comment]
dans tes 2 packages il semblerait trainer aussi des liens symboliques : 

finishing deferred symbolic links:
   Roundcube-Mel-master/skins/melanie2_larry ->
/home/thomas/Developpement/git/roundcube-mel-deploiement/webmail/../../github/Roundcube-plugins-Mel/skins/melanie2_larry
   Roundcube-Mel-master/vendor/bin/generate_vcards ->
../sabre/vobject/bin/generate_vcards
   Roundcube-Mel-master/vendor/bin/vobject -> ../sabre/vobject/bin/vobject


finishing deferred symbolic links:
   Roundcube-plugins-Mel-master/aide/config_search.php ->
/home/thomas/Developpement/git/roundcube-mel-deploiement/webmail/../deploiement/init/aide/config_search.php
   Roundcube-plugins-Mel-master/aide/doc ->
/home/thomas/Developpement/git/roundcube-mel-deploiement/webmail/../deploiement/init/aide/doc

**Comment by tpayen** [comment]
Effectivement il y a eu un raté sur quelques liens symboliques il faut que je nettoie ça
Les scripts dans deployment/bin sont plutôt fait pour le developpement
Pour une installation le plus simple reste la récupération de l'archive packagée : https://github.com/messagerie-melanie2/Roundcube-Mel/releases/download/1.4.8.1/Roundcube_Mel_1.4.8.1_ORM_0.6.0.11-20200611161352.tar.gz

**Comment by xlyric** [comment]
je vais tester avec l'archive packagé.
comme la j'ai  sur une installe fraiches round + plugin + orm  >> class limMelanie\log\M2log not found

**Comment by xlyric** [comment]
Pas beaucoup mieux avec l'archive packagé : 

avec seulement les plugins suivants : 

$config['plugins'] = array('mel','mel_logs','mel_ldap_auth','mel_larry');


03-Jul-2020 21:25:51 europe/Paris] PHP Fatal error:  Uncaught Error:
Access to undeclared static property: LibMelanie\Config\Ldap::$OTHER_LDAP in /var/www/html/webmail/vendor/messagerie-melanie2/orm-m2/src/Api/Mce/User.php:278
Stack trace: #0
/var/www/html/webmail/vendor/messagerie-melanie2/orm-m2/src/Lib/MceObject.php(143): LibMelanie\Api\Mce\User->getMapFullname()
#1 /var/www/html/webmail/plugins/mel/mel.php(1559): LibMelanie\Lib\MceObject->__get('fullname')
#2 /var/www/html/webmail/plugins/mel/mel.php(708): mel->m2_list_identities() 
#3 /var/www/html/webmail/program/lib/Roundcube/rcube_plugin_api.php(456): mel->login_after(Array) 
#4 /var/www/html/webmail/index.php(156):  rcube_plugin_api->exec_hook('login_after', Array)
#5 {main}    thrown in /var/www/html/webmail/vendor/messagerie-melanie2/orm-m2/src/Api/Mce/User.php on line 278

**Comment by xlyric** [comment]
j'ai tenté de repartir du ldap.php fournis avec l'orm et toujours pareil  :( 
même message.

**Comment by tpayen** [comment]
Bonjour Cyril,
Tu peux soit essayer avec la release 1.4.8.2 qui doit corriger ça, soit ajouter une variable `$OTHER_LDAP` dans le fichier de conf ldap.php avec la même valeur que `$AUTH_LDAP` par exemple

**Comment by xlyric** [comment]
nickel, ça marche de suite avec la version 1.4.8.2
