### ISSUE TITLE
fonctionnement mel_contacts

### ISSUE THREAD

**Issue by xlyric** [messagerie-melanie2/Roundcube-Mel#2]
Thomas, 

à l'activation du plugin mel_contacts
j'ai le message suivant dans les logs lors de je vais sur contacts. 
sans le module et juste avec le module annuaire, j'ai l'autocompletion qui fonctionne

[06-Jul-2020 16:26:50 europe/Paris] PHP Fatal error:  Uncaught Error:
Call to a member function executeQuery() on bool in
/var/www/html/webmail/vendor/messagerie-melanie2/orm-m2/src/Objects/UserMelanie.php:898
Stack trace:
#0
/var/www/html/webmail/vendor/messagerie-melanie2/orm-m2/src/Api/Defaut/User.php(1328):
LibMelanie\Objects\UserMelanie->getDefaultAddressbook()
#1 /var/www/html/webmail/plugins/mel_contacts/mel_contacts.php(213):
LibMelanie\Api\Defaut\User->getDefaultAddressbook()
#2
/var/www/html/webmail/program/lib/Roundcube/rcube_plugin_api.php(456):
mel_contacts->config_get(Array)
#3 /var/www/html/webmail/program/lib/Roundcube/rcube_config.php(410):
rcube_plugin_api->exec_hook('config_get', Array)
#4 /var/www/html/webmail/program/include/rcmail.php(309):
rcube_config->get('autocomplete_ad...')
#5 /var/www/html/webmail/program/steps/addressbook/func.inc(64):
rcmail->get_address_sources()
#6 /var/www/html/webmail/index.php(288): include_once('/var/www/html/w...')
#7 {main}
   thrown in
/var/www/html/webmail/vendor/messagerie-melanie2/orm-m2/src/Objects/UserMelanie.php
on line 898

**Comment by tpayen** [comment]
A priori tu dois avoir un problème de configuration dans le fichier de configuration sql.php de l'orm (dans /etc/LibM2). Je pense qu'il ne trouve pas la configuration du serveur (tu dois surement avoir des logs erreurs dans les logs roundcube)

**Comment by xlyric** [comment]
lors d'un rafraichissement 
il n'y a que ça 
==> sql <==
[06-Jul-2020 21:11:07 +0200]: <22f4jgmg> [1] SELECT * FROM "users" WHERE
"user_id" = '5';
sinon coté erreur , c'étais le message précédents.

Le problème venait bien de sql.php , 

la variable du serveur n'était pas bien déclaré mais avec les bons paramètres 
  'monserveur' => array(  
vers  
  'm2db-srv.mce.com' => array(
